# App Name
spring.application.name=JobApplicationTracker

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=jobtracker_user
spring.datasource.password=jobtracker_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.open-in-view=true

